### ISSUE TITLE
baranims.js code in Shiny example?

### ISSUE THREAD

**Issue by woraperth** [rstudio/r2d3#18]
Hello,

Excellent work for this R2D3 library! I tried using the R code provided in the documentation in the Shiny section. However, I could not find the code for `baranims.js` anywhere.

May I ask where can I find it?

Cheers,
Perth

**Comment by jjallaire** [comment]
Just checked in a change to the package/docs that makes this file available (it's in inst/examples/baranims.js).

@javierluraschi I noticed that the baranims.js script doesn't make use of dynamic width and height information (which in this case comes from the `width` and `height` arguments to `d3Output()`, which are respectively 100% and 400px). Could we change the baranims.js script to use the `width` and `height` variables?
