### ISSUE TITLE
Add chart ID assignment for finer DOM manipulation

### ISSUE THREAD

**Issue by mortonanalytics** [rstudio/r2d3#28]
**Use Case:**
Typically, to write a re-usable charts, I have to assign `id`'s (or `class`) to chart and it's elements to give users finer DOM manipulation control:

`.attr("id", 'tag-point-' + chartElement.id + '-' + layer.label.replace(/\s+/g, '')  )`

This creates a whole set of points that can now be manipulated by downstream calls without manipulating the plot next door that has the same `circle` objects with the same layer label - common when using re-usable charts.

I think a _**major motivation for using d3.js is the DOM manipulation**_ (not just customized plots), so it's important that users have this ability. It only gets more complicated when users start using clip paths, gradients, and other `defs` for their plots.

**Feature Request:**
I have used the `el` to assign the chart id via `htmlwidgets` that passes the output ID from Shiny, I'm not seeing a similar avenue here - though I may have just missed it. I would request that a chart id argument be added so that it may be used for assignment to DOM elements. A user should be able to use `d3.select('#mychart')` to select their chart in the DOM.

**Comment by jjallaire** [comment]
If we made the `elementId` parameter from `htmlwidgets::createWidget()` available (see https://www.rdocumentation.org/packages/htmlwidgets/versions/1.2/topics/createWidget) would that do the trick?

**Comment by mortonanalytics** [comment]
Yes, that's what I use now and it works.

**Comment by jjallaire** [comment]
Okay, just committed a change to add the `elementId` parameter to the `r2d3()` function.
