### ISSUE TITLE
canvas return option?

### ISSUE THREAD

**Issue by nstrayer** [rstudio/r2d3#29]
Since currently only the `svg` container reference is passed to the user if you want to switch over your visualization to canvas rendering instead you need to jump through a few hoops to append a canvas to the parent of the svg. 

Would adding an option along the lines of `r2d3(data = ..., canvas = TRUE)` which then instead of giving the user an svg object, gives them a canvas be within the goal of this project? Or is the idea that `r2d3` is for more quick sketching of ideas which then can be implemented more formally with something like `htmlwidgets` when they get more complicated?

**Comment by jjallaire** [comment]
You should be able to do `container = "canvas"` and then we will pass you the canvas. @javierluraschi Is that correct?

**Comment by nstrayer** [comment]
You are! I just found this. My bad for not investigating further to see.
