### ISSUE TITLE
flashing screen in Rstudio? no plot to be seen. works in html...

### ISSUE THREAD

**Issue by picousse** [rstudio/r2d3#40]
I don't seem to be getting this right:
code:
R file:
`f =' {
  "name": "aaaa",
  "children": [
    {
      "name": "bbbb",
      "children": [
        {
          "name": "cccc",
          "children": [
            {
              "name": "dddd",
            }
            ]
        }
        ]
    }
    ]
} '

r2d3(data=f, script = "learn_plot.js")`

learn_plot.js

`var treeData = data;

// set the dimensions and margins of the diagram
var margin = {top: 40, right: 90, bottom: 50, left: 90},
    width = 660 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;

// declares a tree layout and assigns the size
var treemap = d3.tree()
    .size([width, height]);

//  assigns the data to a hierarchy using parent-child relationships
var nodes = d3.hierarchy(treeData);

// maps the node data to the tree layout
nodes = treemap(nodes);

// append the svg obgect to the body of the page
// appends a 'group' element to 'svg'
// moves the 'group' element to the top left margin
var svg = d3.select("body").append("svg")
      .attr("width", width + margin.left + margin.right)
      .attr("height", height + margin.top + margin.bottom),
    g = svg.append("g")
      .attr("transform",
            "translate(" + margin.left + "," + margin.top + ")");

// adds the links between the nodes
var link = g.selectAll(".link")
    .data( nodes.descendants().slice(1))
  .enter().append("path")
    .attr("class", "link")
    .attr("d", function(d) {
       return "M" + d.x + "," + d.y
         + "C" + d.x + "," + (d.y + d.parent.y) / 2
         + " " + d.parent.x + "," +  (d.y + d.parent.y) / 2
         + " " + d.parent.x + "," + d.parent.y;
       });

// adds each node as a group
var node = g.selectAll(".node")
    .data(nodes.descendants())
  .enter().append("g")
    .attr("class", function(d) {
      return "node" +
        (d.children ? " node--internal" : " node--leaf"); })
    .attr("transform", function(d) {
      return "translate(" + d.x + "," + d.y + ")"; });

// adds the circle to the node
node.append("circle")
  .attr("r", 10);

// adds the text to the node
node.append("text")
  .attr("dy", ".35em")
  .attr("y", function(d) { return d.children ? -20 : 20; })
  .style("text-anchor", "middle")
  .text(function(d) { return d.data.name; });`

any help? 
I simply don't see any plot, and I don't know what is going on... Just a flashing plot screen in rstudio.

I installed v1.2 preview server.

**Comment by javierluraschi** [comment]
@picousse `r2d3::r2d3()` takes an R object, not a character with JSON data, use `jsonlite::fromJSON` instead with something similar to:

```r
r2d3::r2d3(
  data = jsonlite::fromJSON("{\n\"name\": \"aaaa\",\n\"children\": [\n{\n\"name\": \"bbbb\",\n\"children\": [\n{\n\"name\": \"cccc\",\n\"children\": [\n{\n\"name\": \"dddd\"\n}\n]\n}\n]\n}\n]\n}"), script="~/RStudio/test-d3-34.js",
  script = "learn_plot.js"
)
```

**Comment by picousse** [comment]
owkay, I got it up and running using a gallery example.
