### ISSUE TITLE
Anyway to hide the code chunk in an RMarkdown document?

### ISSUE THREAD

**Issue by RobertMyles** [rstudio/r2d3#46]
I'm trying to hide the d3 code chunk in an RMarkdown document that I'm making. I've tried: 

`
{d3 echo = FALSE}
`

and 
`
d3 include = FALSE}
`

But neither work, as they would with R code chunks. The first shows the code as normal and the second hides it, but doesn't make the plot. Any tips?

**Comment by kevinushey** [comment]
The reticulate Python engine is probably useful as prior art:

https://github.com/rstudio/reticulate/blob/5541e21544ff64b21ad722a502b15c2b687f5ee1/R/knitr-engine.R#L30-L31

IIUC, at least currently, the onus is on the engine to ensure the generated output respects the provided knitr options, but I wonder if knitr could do this 'by default' for some of these.

**Comment by yihui** [comment]
I think I can deal with it in **knitr** in a general way (engine-agnostic).

**Comment by RobertMyles** [comment]
Works perfectly now, thanks @yihui .
