### ISSUE TITLE
r2d3.onRender doesn't seem to work 

### ISSUE THREAD

**Issue by cmtso** [rstudio/r2d3#67]
I have been trying out the r2d3 examples. But it seems any examples that have the r2d3.onRender is the .js file does not show any colour above the base layer.

For example, in the calendar example, all I get is the calendar but no colour. Please provide some pointers. Thanks!

**Comment by cmtso** [comment]
UDPATE:

I think the issue is with reading in the data using r2d3(data=...). Basically, I can run all the examples that do not require reading data from R perfectly. But for the ones requiring data from R, the data does not show up.

I am running it on Windows in Rstudio 1.2 and using `servr` package as the browser. Please help. Thanks.

**Comment by javierluraschi** [comment]
The bubbles examples makes use of `onRender()` but happens to work just fine for me using Windows 10, does the code bellow work for you? Could you share the exact error?

```r
download.file("https://raw.githubusercontent.com/rstudio/r2d3/master/vignettes/gallery/bubbles/bubbles.js", "bubbles.js")

r2d3::r2d3("bubbles.js", data = read.csv("https://raw.githubusercontent.com/rstudio/r2d3/master/vignettes/gallery/bubbles/flare.csv"), d3_version = 4)
```

<img width="1440" alt="Screen Shot 2019-07-02 at 4 17 53 PM" src="https://user-images.githubusercontent.com/3478847/60552917-bafb8380-9ce5-11e9-955a-3d6c4127adfd.png">
<img width="743" alt="Screen Shot 2019-07-02 at 4 19 51 PM" src="https://user-images.githubusercontent.com/3478847/60552918-bafb8380-9ce5-11e9-883f-243affd7cf32.png">

**Comment by cmtso** [comment]
Great. I get it done now. Thanks!
